### ISSUE TITLE
1812032 :  On course manager, for the teacher, student who are online and subscribed not being updated.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#45]
Defect ID: 1812032
Test Description:  On course manager, for the teacher, student who are online and subscribed not being updated.
Build: 1.2
Severity: Critical
Steps to Reproduce:
1. Click on URL https://ca.tsybanov.com/
2. Log in as a Teacher(jt@tmail.com, 123456-pwd)
3. Push SPA course, live
4. Log in with another student login, on another device(jstu@tmail.com, 123456-pwd)
5. Make the student subscribe to the course
6. Refresh the teacher’s coursemanager page
7. Observe the page
Actual Result: Zero students are online
Expected Result: 1 Student should be seen online
Frequency: Always

**Comment by nasyarobby** [comment]
The column was intended to show number of students who subscribed to the course, not students who are online in the room.
