### ISSUE TITLE
 1812033 :  In subscribed courses, for the student, courses that are live is not updated.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#46]
Defect ID: 1812033
Test Description:  In subscribed courses, for the student, courses that are live is not updated.
Severity: Critical
Build: 1.2
Steps to Reproduce:
1. Click on URL  https://ca.tsybanov.com/
2. Log in as a Teacher(jt@tmail.com, 123456-pwd)
3. Push SPA course, live
4. Log in with another student login, on another device(jstu@tmail.com, 123456-pwd)
5. Make the student subscribe to the course
6. Refresh the student’s Subscribed Courses page
7. Observe the page
Actual Result: The course is not updated to be online
Expected Result: Once a student is subscribed to a course and if it is live, it should reflect
Frequency: Always

**Comment by nasyarobby** [comment]
fixed by #28
