### ISSUE TITLE
1812034 :  On course manager, for the teacher, when a test is pushed online, it is not reflected.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#47]
Defect ID: 1812034
Test Description:  On course manager, for the teacher, when a test is pushed online, it is not reflected.
Severity: Critical
Build: 1.2
Steps to Reproduce:
1. Click on URL https://ca.tsybanov.com/
2. Log in as a Teacher(jt@tmail.com, 123456-pwd)
3. Push SPA course, live
4. Click on Offline
5. Select Quiz test set1
6. Click on Online
7. Observe the behavior
Frequency- Always
Actual Result: The test that is online is not reflected 
Expected Result: It must show Test 1 to be online.

**Comment by nasyarobby** [comment]
Fixed with commit #28
