### ISSUE TITLE
Defect ID: 1812041 Test Description:  On course manager, for the teacher, student who are online and subscribed not being 

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#49]
Defect ID: 1812041
Test Description:  On course manager, for the teacher, student who are online and subscribed not being updated within a quiz
Severity: Critical
Build: 1.2.1
Steps to Reproduce:
1. Click on URL https://ca.tsybanov.com/
2. Log in as a Teacher(jt@tmail.com, 123456-pwd)
3. Push CS 695 and test, live
4. Log in with another student login, on another device(jstu@tmail.com, 123456-pwd)
5. Make the student subscribe to the course
6. Click on Students icon
7. Observe the page
Actual Result: Shows only the count of students who are online
Expected Result: Must show the count and the details of the student who are online
Frequency: Always

**Comment by nasyarobby** [comment]
fixed by #28
