### ISSUE TITLE
1812042 :  On course manager, for the teacher, student who have answered the quiz question not visible, it still shows 0 students answered.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#50]
Defect ID: 1812042
Test Description:  On course manager, for the teacher, student who have answered the quiz question not visible, it still shows 0 students answered.
Severity: Critical
Steps to Reproduce:
1. Click on URL https://ca.tsybanov.com/
2. Log in as a Teacher(jt@tmail.com, 123456-pwd)
3. Push CS 695 and test, live
4. Log in with another student login, on another device(jstu@tmail.com, 123456-pwd)
5. Make the student answer quiz question
7. Observe the Teacher page after clicking on Result
Actual Result: It shows 0 students answered the question
Expected Result: It must show 1 student answered the question
Frequency: Always

**Comment by nasyarobby** [comment]
fixed by #40
