### ISSUE TITLE
 1811291 :  There are two register options on the home page.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#51]
Defect ID: 1811291 
Test Description:  There are two register options on the home page.
Severity: Major
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Observe Homepage
Actual Result: There are two register options.
Expected Result: There should be only 1 register option
Frequency: Always

**Comment by nasyarobby** [comment]
fixed #28
