### ISSUE TITLE
1811292 : The register option shows an error.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#52]
Defect ID: 1811292
Test Description: The register option shows an error.
Severity: Blocker
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Click on the register option on the top right corner of the home page.
Actual Result: Error pop-up, “Cannot GET /register” appears.
Expected Result: Registration Page for User should open on clicking ‘register’ option.
Frequency: Always

**Comment by nasyarobby** [comment]
fixed by #28
