### ISSUE TITLE
1811293 : Course-Manager option is not available

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#53]
Defect ID: 1811293
Test Description: Course-Manager option is not available
Severity: Blocker
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Login as a Teacher
Click on “Course-Manager”
Error pop-up, Apache/2.4.18 (Ubuntu) Server at ca.tsybanov.com Port 443’ appears
Reload the page
Redirects back to login page
Actual Result: Error pop-up, ‘Apache/2.4.18 (Ubuntu) Server at ca.tsybanov.com Port 443’ appears
Expected Result: Course-Manager option should open
Frequency: Always

**Comment by nasyarobby** [comment]
fixed #28
