### ISSUE TITLE
1811294 : Tooltip in Quiz Manager shows ‘icon name’

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#54]
Defect ID: 1811294
Test Description: Tooltip in Quiz Manager shows ‘icon name’
Severity: Minor
Build : v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Login as a Teacher
Click on “Quiz-Manager”
Create a quiz
Observe the view icon
Actual Result: Tool tip title is ‘icon name’
Expected Result: Tool tip title should be ‘view’
Frequency; Always

**Comment by nasyarobby** [comment]
Fixed #28
