### ISSUE TITLE
1811295 : Error pop up appears when view icon is clicked in Quiz Manager 

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#55]
Defect ID: 1811295
Test Description: Error pop up appears when view icon is clicked in Quiz Manager 
Severity: Major
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Login as a Teacher
Click on “Quiz-Manager”
Create a quiz
Click on view icon
Actual Result: Error pop-up, Apache/2.4.18 (Ubuntu) Server at ca.tsybanov.com Port 443’ appears
Expected Result: View icon should show me a preview of the quiz question. 
Frequency: Always

**Comment by nasyarobby** [comment]
fixed by #33
