### ISSUE TITLE
1811296 : After login, inconsistent behavior while clicking on register option

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#56]
Defect ID: 1811296
Test Description: After login, inconsistent behavior while clicking on register option
Severity: Major
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Login as a Teacher
Click on Home
Click on register
Click on view icon
Actual Result: Redirects to the main page.
Expected Result: Register option should not be available
Frequency: Always

**Comment by nasyarobby** [comment]
fixed #28
