### ISSUE TITLE
 1811297 : Two users have the same email ID.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#57]
Defect ID: 1811297
Test Description: Two users have the same email ID.
Severity: Critical
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Click on Register 
Create user (email id: student@gmail.com; password: 123456)
Register another user using same email ID
Actual Result: Two users are allowed to register with same email ID
Expected Result: Prompt should have appeared stating, ‘email ID already exists’, when trying to register using existing email ID of a registered user.

**Comment by nasyarobby** [comment]
fixed by #28
