### ISSUE TITLE
1811299  :  There are two login options on the home page.

### ISSUE THREAD

**Issue by Jhukhirtha** [Tsybanov/Course-Assistant#59]
Defect ID: 1811299 
Test Description:  There are two login options on the home page.
Severity: Major
Build: v1
Steps to Reproduce:
Click on URL https://ca.tsybanov.com/
Observe Home page
Actual Result: There are two register options.
Expected Result: There should be only 1  option
Frequency: Always

**Comment by Jhukhirtha** [comment]
Actual Result: There are two login options
Expected Result: There should be only 1 login option

**Comment by nasyarobby** [comment]
fixed by #28
